# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: true
dist: trusty


r_packages:
  - tidyverse
  - covr
  - lintr

before_install:
  - export bcftools_version=1.3.1
  - wget "https://github.com/samtools/bcftools/releases/download/${bcftools_version}/bcftools-${bcftools_version}.tar.bz2" -O bcftools.tar.bz2
  - tar -xjvf bcftools.tar.bz2
  - cd bcftools-${bcftools_version}
  - make
  - sudo make install
  
after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'


notifications:
  email: true
