# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr
  - lintr

before_install:
  - ls
  - ls ..
  - ls ../../
  - echo $PATH
  - ls /usr/local/bin
  - mkdir bin
  - export PATH=${PWD}/bin:${PATH}
  - export bcftools_version=1.3.1
  - wget "https://github.com/samtools/bcftools/releases/download/${bcftools_version}/bcftools-${bcftools_version}.tar.bz2" -O bcftools.tar.bz2
  - tar -xjvf bcftools.tar.bz2
  - cd bcftools-${bcftools_version}
  - make
  - cd ..
  - ln -s bcftools-${bcftools_version}/bcftools /usr/local/bin/bcftools

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'


notifications:
  email: false
