# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: 
  packages: true
  directories:
    - ~/.cegwas
sudo: true
dist: trusty

r_packages:
  - tidyverse
  - covr
  - lintr
  - RSQLite
  - data.table

r:
  - release

before_install:
  - export bcftools_version=1.3.1
  - wget "https://github.com/samtools/bcftools/releases/download/${bcftools_version}/bcftools-${bcftools_version}.tar.bz2" -O bcftools.tar.bz2
  - tar -xjvf bcftools.tar.bz2
  - cd bcftools-${bcftools_version}
  - make
  - sudo make install
  - cd ${TRAVIS_BUILD_DIR}
  - rm bcftools.tar.bz2
  - rm -rf bcftools-${bcftools_version}
  - export LINTR_COMMENT_BOT=false;

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::coveralls()'

warnings_are_errors: false

notifications:
  email: true
