# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

r_packages:
  - covr
  - lintr

before_install:
  # Install bcftools
  - ls /usr/local/bin
  - mkdir /usr/local/bcftools
  - cd /usr/local/bcftools
  - wget "https://github.com/samtools/bcftools/releases/download/${bcftools_version}/bcftools-${bcftools_version}.tar.bz2" -O bcftools.tar.bz2
  - tar -xjvf bcftools.tar.bz2
  - cd bcftools-${bcftools_version}
  - make
  - sudo make prefix=/usr/local/bin install
  - sudo ln -s bcftools-${bcftools_version}/bcftools /usr/local/bin/bcftools
  - cd

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'


notifications:
  email: true
